package canned

// This file was vibe generated from 1756-rd001_-en.xlsx

type FaultDescription struct {
	Type             int
	Code             int
	Display          string
	Description      string
	CorrectiveAction string
	Major            bool
	TypeName         string
}

// FaultDescriptions is a map for looking up fault descriptions by type and code.
var FaultDescriptions = map[int]map[int]FaultDescription{
	1: {
		1: {
			Type:             1,
			Code:             1,
			Display:          "Major Fault T01:C01 - Power-up Fault: Power lost and restored in RUN mode.",
			Description:      "The controller that is powered on is in Run mode.",
			CorrectiveAction: "Execute the power-up handler.",
			Major:            true,
			TypeName:         "Power Up",
		},
		2: {
			Type:             1,
			Code:             2,
			Display:          "0x00000000",
			Description:      "AC power loss detected. Chassis active until DC power cannot be maintained.",
			CorrectiveAction: "Legacy. Now an unused fault code.",
			Major:            false,
			TypeName:         "Power Up",
		},
		15: {
			Type:             1,
			Code:             15,
			Display:          "Minor Fault T01:C15 - Power-up Fault: I/O Power fault detected.",
			Description:      "A 1769 power supply is connected directly to the controller’s 1768 CompactBus with an invalid configuration. The 1768 power supply that provides power to the controller has failed.",
			CorrectiveAction: "Remove the power supply from the 1768 CompactBus and cycle power to the system. Replace the power supply.",
			Major:            false,
			TypeName:         "Power Up",
		},
		16: {
			Type:             1,
			Code:             16,
			Display:          "Major Fault T01:C16 - Power-up Fault: I/O Communications Configuration fault detected.",
			Description:      "I/O communication configuration fault detected.",
			CorrectiveAction: "Reconfigure the number of communication modules on the 1768 bus side of the controller: • 1768-L43 has a maximum of two modules. •1768-L45 has a maximum of four modules. • Up to four Sercos modules • Up to two NetLinx communication modules",
			Major:            true,
			TypeName:         "Power-up",
		},
		29: {
			Type:             1,
			Code:             29,
			Display:          "Minor Fault T01:C29 - Power-up Fault: Voltage has exceeded operating limits.",
			Description:      "Voltage has exceeded operating limits.",
			CorrectiveAction: "Legacy. Now an unused fault code.",
			Major:            false,
			TypeName:         "Power Up",
		},
		40: {
			Type:             1,
			Code:             40,
			Display:          "Major Fault T01:C40 - Power-up Fault: Energy Storage Module/Battery failed during power down.",
			Description:      "If the controller uses a battery, the battery does not contain enough charge to save the user program on power-down.  If the controller uses an ESM (Energy Storage Module), the ESM does not contain enough charge to save the user program on power-down.",
			CorrectiveAction: "For controllers that use a battery, replace the battery. For controllers that use an ESM (Energy Storage Module): • Allow the ESM to charge fully before powering down the controller. • Replace the ESM if the ESM is removable, or replace the controller if the ESM is not removable.  If the problem persists, contact Rockwell Automation support.",
			Major:            true,
			TypeName:         "Power Up",
		},
		60: {
			Type:             1,
			Code:             60,
			Display:          "Major Fault T01:C60 - Power-up Fault: Non-recoverable fault.",
			Description:      "The controller detected a nonrecoverable major fault. Diagnostic information can be recovered.",
			CorrectiveAction: "Insert a memory card in the controller and restart the controller to write diagnostic information to the memory card. Then clear the fault and download the application. Contact Rockwell Automation support and provide the 9-character code from the scrolling status display on the controller.",
			Major:            true,
			TypeName:         "Power Up",
		},
		61: {
			Type:             1,
			Code:             61,
			Display:          "Major Fault T01:C61 - Power-up Fault: Non-recoverable fault with saved diagnostic information.",
			Description:      "The controller detected a nonrecoverable major fault. Diagnostic information can be recovered.",
			CorrectiveAction: "Insert a memory card in the controller and restart the controller to write diagnostic information to the memory card. Then clear the fault and download the application. Contact Rockwell Automation support and provide the 9-character code from the scrolling status display on the controller.",
			Major:            true,
			TypeName:         "Power Up",
		},
		62: {
			Type:             1,
			Code:             62,
			Display:          "Major Fault T01:C62 - Power-up Fault: Non-recoverable fault with saved diagnostic information and stored user program.",
			Description:      "The controller detected a nonrecoverable major fault. Diagnostic information can be recovered.",
			CorrectiveAction: "Insert a memory card in the controller and restart the controller to write diagnostic information to the memory card. Then clear the fault and download the application. Contact Rockwell Automation support and provide the 9-character code from the scrolling status display on the controller.",
			Major:            true,
			TypeName:         "Power Up",
		},
	},
	3: {
		0: {
			Type:             3,
			Code:             0,
			Display:          "Minor Fault T3:C0 - I/O Fault: Compact I/O™ end cap missing.",
			Description:      "Compact I/O™ end cap missing.",
			CorrectiveAction: "Install the end cap.",
			Major:            false,
			TypeName:         "I/O",
		},
		1: {
			Type:             3,
			Code:             1,
			Display:          "Minor Fault T03:C01 - I/O Fault: POINTBus™ backplane bus off.",
			Description:      "POINTBus™ backplane bus off condition. The connections between the controller and the I/O modules are broken.",
			CorrectiveAction: "Complete these steps to identify the source of the BUS OFF fault: 1.  The number of local expansion modules in the project matches the number of modules that are physically installed in the system. 2.  All mounting bases are locked and I/O modules are securely installed on mounting bases. 3. All 1734 POINT I/O™ modules are configured to use the Autobaud rate. If these steps do not remedy the fault condition, contact Rockwell Automation support.",
			Major:            false,
			TypeName:         "I/O",
		},
		16: {
			Type:             3,
			Code:             16,
			Display:          "Major Fault T03:C16 - I/O Fault: I/O module connection failed on required module.",
			Description:      "A required I/O module connection failed.",
			CorrectiveAction: "Verify the following: •The I/O module is in the chassis. • Electronic keying requirements. • Controller Properties Major Fault tab and the Module Properties Connection tab for more information about the fault.",
			Major:            true,
			TypeName:         "I/O",
		},
		20: {
			Type:             3,
			Code:             20,
			Display:          "Major Fault T03:C20 - I/O Fault: Unable to read ControlBus™ chassis information.  Chassis may be bad.",
			Description:      "Possible fault with the chassis.",
			CorrectiveAction: "Not recoverable. Replace the chassis.",
			Major:            true,
			TypeName:         "I/O",
		},
		21: {
			Type:             3,
			Code:             21,
			Display:          "Major Fault T03:C21 - I/O Fault: Unable to read ControlBus™ chassis information. Chassis may be bad.",
			Description:      "Possible fault with the chassis.",
			CorrectiveAction: "Not recoverable. Replace the chassis.",
			Major:            true,
			TypeName:         "I/O",
		},
		23: {
			Type:             3,
			Code:             23,
			Display:          "Major Fault T03:C23 - I/O Fault: At least one required connection not established before going into RUN mode.",
			Description:      "At least one required connection was not established before going to Run mode.",
			CorrectiveAction: "Wait for the controller I/O light to turn green before changing to Run mode.",
			Major:            true,
			TypeName:         "I/O",
		},
		32: {
			Type:             3,
			Code:             32,
			Display:          "Major Fault T03:C32 - I/O Fault: Controller failed to open an I/O connection to a fault-tolerant I/O module because its partner controller is in a Primary state.",
			Description:      "The controller failed to open an I/O connection to a fault-tolerant I/O module because its partner controller is in a Primary state.",
			CorrectiveAction: "• Make sure that the redundancy module is correctly inserted and connected. • Synchronize the redundancy controllers so that only one controller is in the Primary state.",
			Major:            true,
			TypeName:         "I/O",
		},
		94: {
			Type:             3,
			Code:             94,
			Display:          "Minor Fault T03:C94 - I/O Fault: Module RPI overlap detected.",
			Description:      "The current RPI update of an I/O module overlaps with its previous RPI update.",
			CorrectiveAction: "Set the RPI rate of the I/O modules to a higher numerical value. Rockwell Automation recommends that the CompactLogix™ 5370 L2 and CompactLogix 5370 L3 control systems do not run with Module RPI Overlap faults.",
			Major:            false,
			TypeName:         "I/O",
		},
		100: {
			Type:             3,
			Code:             100,
			Display:          "Minor Fault T03:C100 - I/O Fault: I/O module does not support data integrity.",
			Description:      "The I/O module does not support data integrity.",
			CorrectiveAction: "Legacy. Now an unused fault code.",
			Major:            false,
			TypeName:         "I/O",
		},
	},
	4: {
		4: {
			Type:             4,
			Code:             4,
			Display:          "Minor Fault T04:C04 - Program Fault: Arithmetic overflow.  Result of an arithmetic instruction out of range.",
			Description:      "The result of an arithmetic operation is out of range.",
			CorrectiveAction: "Examine the arithmetic operations (order) or adjust the values.",
			Major:            false,
			TypeName:         "Program",
		},
		5: {
			Type:             4,
			Code:             5,
			Display:          "Minor Fault T04:C05 - Program Fault: GSV/SSV object address invalid.",
			Description:      "In a GSV/SSV instruction, the specified instance was not found.",
			CorrectiveAction: "Check the instance name.",
			Major:            false,
			TypeName:         "Program",
		},
		6: {
			Type:             4,
			Code:             6,
			Display:          "Minor Fault T04:C06 - Program Fault: GSV/SSV operand invalid.",
			Description:      "In a GSV/SSV instruction, either the: • Specified Class name is not supported. • Specified Attribute name is not valid.",
			CorrectiveAction: "Check the Class name and Attribute name.",
			Major:            false,
			TypeName:         "Program",
		},
		7: {
			Type:             4,
			Code:             7,
			Display:          "Minor Fault T04:C07 - Program Fault: GSV/SSV destination tag too small to hold all data.",
			Description:      "The GSV/SSV destination tag was too small to hold the data.",
			CorrectiveAction: "Fix the destination so it has enough space.",
			Major:            false,
			TypeName:         "Program",
		},
		16: {
			Type:             4,
			Code:             16,
			Display:          "Major Fault T04:C16 - Program Fault: Unknown instruction encountered.",
			Description:      "Unknown instruction encountered.",
			CorrectiveAction: "Remove the unknown instruction. This probably happened due to a program conversion process.",
			Major:            true,
			TypeName:         "Program",
		},
		20: {
			Type:             4,
			Code:             20,
			Display:          "Major Fault T04:C20 - Program Fault: Array subscript too large, or CONTROL data type POS or LEN invalid.",
			Description:      "The array subscript is too large or the control data type .POS or .LEN value is invalid.",
			CorrectiveAction: "Adjust the value to be within the valid range. Do not exceed the array size or go beyond the dimensions defined.",
			Major:            true,
			TypeName:         "Program",
		},
		21: {
			Type:             4,
			Code:             21,
			Display:          "Major Fault T04:C21 - Program Fault: CONTROL data type LEN or POS less than 0.",
			Description:      "Control structure .LEN or .POS < 0.",
			CorrectiveAction: "Adjust the value so it is > 0.",
			Major:            true,
			TypeName:         "Program",
		},
		24: {
			Type:             4,
			Code:             24,
			Display:          "Major Fault T04:C24 - Program Fault: Unknown data type passed to subroutine.",
			Description:      "Unknown data type passed to subroutine.",
			CorrectiveAction: "Legacy. Now an unused fault code.",
			Major:            true,
			TypeName:         "Program",
		},
		30: {
			Type:             4,
			Code:             30,
			Display:          "Minor Fault T04:C30 - Program Fault: ASCII instruction failed.",
			Description:      "An ASCII instruction failed. Bad parameters passed through to the ASCII port.",
			CorrectiveAction: "Verify the ASCII configuration settings.",
			Major:            false,
			TypeName:         "Program",
		},
		31: {
			Type:             4,
			Code:             31,
			Display:          "Major Fault T04:C31 - Program Fault: JSR or RET did not pass as many parameters as expected.",
			Description:      "The parameters of the JSR instruction do not match those of the associated SBR or RET instruction.",
			CorrectiveAction: "Pass the appropriate number of parameters. If you pass too many parameters, the extra ones are ignored without any error.",
			Major:            true,
			TypeName:         "Program",
		},
		32: {
			Type:             4,
			Code:             32,
			Display:          "Minor Fault T04:C32 - Program Fault: Routine type not supported.",
			Description:      "Routine type not supported.",
			CorrectiveAction: "Legacy. Now an unused fault code.",
			Major:            false,
			TypeName:         "Program",
		},
		34: {
			Type:             4,
			Code:             34,
			Display:          "Major Fault T04:C34 - Program Fault: A timer instruction had a negative value for its PRE or ACC.",
			Description:      "A timer instruction has a negative preset or accumulated value.",
			CorrectiveAction: "Fix the program so that it cannot load a negative value into the timer preset or accumulated value.",
			Major:            true,
			TypeName:         "Program",
		},
		35: {
			Type:             4,
			Code:             35,
			Display:          "Minor Fault T04:C35 - PID delta time was less than 0.",
			Description:      "PID delta time less than zero.",
			CorrectiveAction: "Adjust the PID delta time so that it is > 0.",
			Major:            false,
			TypeName:         "Program",
		},
		36: {
			Type:             4,
			Code:             36,
			Display:          "Minor Fault T04:C36 - PID setpoint out of range for target module.",
			Description:      "PID setpoint out of range.",
			CorrectiveAction: "Adjust the setpoint so that it is within range.",
			Major:            false,
			TypeName:         "Program",
		},
		42: {
			Type:             4,
			Code:             42,
			Display:          "Major Fault T04:C42 - Program Fault: JMP to a label that did not exist or was deleted.",
			Description:      "JMP to a label that did not exist or was deleted.",
			CorrectiveAction: "Correct the JMP target or add the missing label.",
			Major:            true,
			TypeName:         "Program",
		},
		51: {
			Type:             4,
			Code:             51,
			Display:          "Minor Fault T04:C51 - Program Fault: LEN value outside DATA limit.",
			Description:      "The .LEN value of the string tag is greater than the DATA size of the string tag.",
			CorrectiveAction: "1. Check that no instruction is writing to the LEN member of the string tag. 2. In the LEN value, enter the number of characters that the string contains.",
			Major:            false,
			TypeName:         "Program",
		},
		52: {
			Type:             4,
			Code:             52,
			Display:          "Minor Fault T04:C52 - Program Fault: Defined string size is invalid.",
			Description:      "The output string is larger than the destination.",
			CorrectiveAction: "Create a string data type that is large enough for the output string. Use the new string data type as the data type for the destination.",
			Major:            false,
			TypeName:         "Program",
		},
		53: {
			Type:             4,
			Code:             53,
			Display:          "Minor Fault T04:C53 - Program Fault: Numeric result cannot fit in destination.",
			Description:      "The output number is beyond the limits of the destination data type.",
			CorrectiveAction: "Either: • Reduce the size of the ASCII value. • Use a larger data type for the destination.",
			Major:            false,
			TypeName:         "Program",
		},
		54: {
			Type:             4,
			Code:             54,
			Display:          "Minor Fault T04:C54 - Program Fault: BufferSize value reduced amount of data.",
			Description:      "BufferSize value reduced amount of data.",
			CorrectiveAction: "Legacy. Now an unused fault code.",
			Major:            false,
			TypeName:         "Program",
		},
		55: {
			Type:             4,
			Code:             55,
			Display:          "Minor Fault T04:C55 - Program Fault: SerialPort Control Len value was incorrect.",
			Description:      "SerialPort Control .LEN value was incorrect.",
			CorrectiveAction: "Legacy. Now an unused fault code.",
			Major:            false,
			TypeName:         "Program",
		},
		56: {
			Type:             4,
			Code:             56,
			Display:          "Minor Fault T04:C56 - Program Fault: Invalid Start and/or Quantity value.",
			Description:      "The Start or Quantity value is invalid.",
			CorrectiveAction: "Check the following: • The Start value is between 1 and the DATA size of the Source. • The Start value plus the Quantity Value is less than or equal to the DATA size of the Source.",
			Major:            false,
			TypeName:         "Program",
		},
		57: {
			Type:             4,
			Code:             57,
			Display:          "Minor Fault T04:C57 - Program Fault: Cannot execute AHL when SerialPort set to NoHandshaking.",
			Description:      "The AHL instruction failed to execute because the serial port is set to no handshaking.",
			CorrectiveAction: "Either: • Change the Control Line setting of the serial port. • Delete the AHL instruction.",
			Major:            false,
			TypeName:         "Program",
		},
		82: {
			Type:             4,
			Code:             82,
			Display:          "Major Fault T04:C82 - Program Fault: Could not re-enter an executing SFC routine.",
			Description:      "A sequential function chart (SFC) called a subroutine and the subroutine tried to jump back to the calling SFC. This occurs when the SFC uses either a JSR or FOR instruction to call the subroutine.",
			CorrectiveAction: "Remove the jump back to the calling SFC.",
			Major:            true,
			TypeName:         "Program",
		},
		83: {
			Type:             4,
			Code:             83,
			Display:          "Major Fault T04:C83 - Program Fault: Value out of range.",
			Description:      "The data tested was not inside the required limits. This occurs with array subscripts used with Boolean arrays and bit level addressing.",
			CorrectiveAction: "Adjust the value to be within the valid range. Do not exceed the array size or go beyond the dimensions defined.",
			Major:            true,
			TypeName:         "Program",
		},
		84: {
			Type:             4,
			Code:             84,
			Display:          "Major Fault T04:C84 - Program Fault: Stack overflow.  Stack too small to perform operation.",
			Description:      "Stack overflow.",
			CorrectiveAction: "Reduce the subroutine-nesting levels or the number of parameters passed.",
			Major:            true,
			TypeName:         "Program",
		},
		85: {
			Type:             4,
			Code:             85,
			Display:          "Major Fault T04:C85 - Program Fault: Invalid routine type.",
			Description:      "Invalid routine type.",
			CorrectiveAction: "Use a valid routine type.",
			Major:            true,
			TypeName:         "Program",
		},
		86: {
			Type:             4,
			Code:             86,
			Display:          "Minor Fault T04:C86 - Program Fault: Access violation in user program.",
			Description:      "Access violation in user program.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support. ",
			Major:            false,
			TypeName:         "Program",
		},
		87: {
			Type:             4,
			Code:             87,
			Display:          "Minor Fault T04:C87 - Program Fault: External routine DLL load failed.  Perhaps a DLL on which it depends is missing.",
			Description:      "External routine DLL load failed. ",
			CorrectiveAction: " DLL missing or malformed. Confirm and adjust.",
			Major:            false,
			TypeName:         "Program",
		},
		88: {
			Type:             4,
			Code:             88,
			Display:          "Minor Fault T04:C88 - Program Fault: Exception in external routine DLL.",
			Description:      "Exception in external routine DLL.",
			CorrectiveAction: "Troubleshoot the external routine DLL.",
			Major:            false,
			TypeName:         "Program",
		},
		89: {
			Type:             4,
			Code:             89,
			Display:          "Major Fault T04:C89 - Program Fault: Target step does not exist in specified routine.",
			Description:      "In an SFR instruction, the target routine does not contain the target step.",
			CorrectiveAction: "Correct the SFR target or add the missing step.",
			Major:            true,
			TypeName:         "Program",
		},
		90: {
			Type:             4,
			Code:             90,
			Display:          "Major Fault T04:C90 - Program Fault: A safety instruction occurs outside a safety task.",
			Description:      "A safety instruction occurred outside a safety task.",
			CorrectiveAction: "Only use the instruction in a safety task.",
			Major:            true,
			TypeName:         "Program",
		},
		91: {
			Type:             4,
			Code:             91,
			Display:          "Major Fault T04:C91 - Program Fault: Equipment phase instruction cannot be called from a program.",
			Description:      "Equipment Phase instruction is being called from outside an Equipment Phase program.",
			CorrectiveAction: "Only use the instruction in an Equipment Phase program.",
			Major:            true,
			TypeName:         "Program",
		},
		94: {
			Type:             4,
			Code:             94,
			Display:          "Major Fault T04:C94 - Program Fault: Nesting limits exceeded.",
			Description:      "Nesting limits exceeded.",
			CorrectiveAction: "Restructure the project to reduce the subroutine-nesting levels.",
			Major:            true,
			TypeName:         "Program",
		},
		990: {
			Type:             4,
			Code:             990,
			Display:          "Major Fault T04:C990 - Program Fault: User-defined fault.",
			Description:      "User-defined major fault.",
			CorrectiveAction: "User-defined action.",
			Major:            true,
			TypeName:         "Program",
		},
		991: {
			Type:             4,
			Code:             991,
			Display:          "Major Fault T04:C991 - Program Fault: User-defined fault.",
			Description:      "User-defined major fault.",
			CorrectiveAction: "User-defined action.",
			Major:            true,
			TypeName:         "Program",
		},
		992: {
			Type:             4,
			Code:             992,
			Display:          "Major Fault T04:C992 - Program Fault: User-defined fault.",
			Description:      "User-defined major fault.",
			CorrectiveAction: "User-defined action.",
			Major:            true,
			TypeName:         "Program",
		},
		993: {
			Type:             4,
			Code:             993,
			Display:          "Major Fault T04:C993 - Program Fault: User-defined fault.",
			Description:      "User-defined major fault.",
			CorrectiveAction: "User-defined action.",
			Major:            true,
			TypeName:         "Program",
		},
		994: {
			Type:             4,
			Code:             994,
			Display:          "Major Fault T04:C994 - Program Fault: User-defined fault.",
			Description:      "User-defined major fault.",
			CorrectiveAction: "User-defined action.",
			Major:            true,
			TypeName:         "Program",
		},
		995: {
			Type:             4,
			Code:             995,
			Display:          "Major Fault T04:C995 - Program Fault: User-defined fault.",
			Description:      "User-defined major fault.",
			CorrectiveAction: "User-defined action.",
			Major:            true,
			TypeName:         "Program",
		},
		996: {
			Type:             4,
			Code:             996,
			Display:          "Major Fault T04:C996 - Program Fault: User-defined fault.",
			Description:      "User-defined major fault.",
			CorrectiveAction: "User-defined action.",
			Major:            true,
			TypeName:         "Program",
		},
		997: {
			Type:             4,
			Code:             997,
			Display:          "Major Fault T04:C997 - Program Fault: User-defined fault.",
			Description:      "User-defined major fault.",
			CorrectiveAction: "User-defined action.",
			Major:            true,
			TypeName:         "Program",
		},
		998: {
			Type:             4,
			Code:             998,
			Display:          "Major Fault T04:C998 - Program Fault: User-defined fault.",
			Description:      "User-defined major fault.",
			CorrectiveAction: "User-defined action.",
			Major:            true,
			TypeName:         "Program",
		},
		999: {
			Type:             4,
			Code:             999,
			Display:          "Major Fault T04:C999 - Program Fault: User-defined fault.",
			Description:      "User-defined major fault.",
			CorrectiveAction: "User-defined action.",
			Major:            true,
			TypeName:         "Program",
		},
	},
	6: {
		1: {
			Type:             6,
			Code:             1,
			Display:          "Major Fault T06:C01 - Watchdog Fault: Task watchdog expired.  May have been caused by an infinite loop, a complex program, or a higher priority task.",
			Description:      "User task has not completed in the specified period. A program error caused an infinite loop, or the program is too complex to run as quickly as specified, or a higher priority task is keeping this task from finishing.",
			CorrectiveAction: "Take one or more of these steps: •  Increase the task watchdog. • Shorten the execution time. • Make the priority of this task higher. • Simplify higher priority tasks. • Move some code to another controller.",
			Major:            true,
			TypeName:         "Watchdog",
		},
		2: {
			Type:             6,
			Code:             2,
			Display:          "Minor Fault T06:C02 - Watchdog Fault: Periodic task overlap.  Task scheduled again before it finished executing.",
			Description:      "Periodic task overlap. The task was scheduled again before it finished executing.",
			CorrectiveAction: "Make changes, such as simplify programs, lengthen the period, or raise the relative priority.",
			Major:            false,
			TypeName:         "Watchdog",
		},
		3: {
			Type:             6,
			Code:             3,
			Display:          "Minor Fault T06:C03 - Watchdog Fault: Event task overlap. Task triggered again before it finished executing.",
			Description:      "Event task overlap. The task triggered again before it finished executing.",
			CorrectiveAction: "Make changes such as simplify programs, lengthen the period, raise the relative priority, or slow the triggering event.",
			Major:            false,
			TypeName:         "Watchdog",
		},
	},
	7: {
		40: {
			Type:             7,
			Code:             40,
			Display:          "Major Fault T07:C40 - Nonvolatile Fault: Store to nonvolatile memory failed.",
			Description:      "Store to nonvolatile memory failed.",
			CorrectiveAction: "1. Try again to store the project to nonvolatile memory. 2. If the project fails to store to nonvolatile memory, replace the memory card. If you are using a 1756-L7x controller, verify that the memory card is unlocked.",
			Major:            true,
			TypeName:         "Flash Save",
		},
		41: {
			Type:             7,
			Code:             41,
			Display:          "Major Fault T07:C41 - Nonvolatile Fault: Load from nonvolatile memory failed due to controller type mismatch.",
			Description:      "Load from nonvolatile memory failed due to controller type mismatch.",
			CorrectiveAction: "Change to a controller of the correct type or download the project and store it on the memory card.",
			Major:            true,
			TypeName:         "Flash Save",
		},
		42: {
			Type:             7,
			Code:             42,
			Display:          "Major Fault T07:C42 - Nonvolatile Fault: Load from nonvolatile memory failed due to controller revision mismatch.",
			Description:      "Load from nonvolatile memory failed because the firmware revision of the project in nonvolatile memory does not match the firmware revision of the controller.",
			CorrectiveAction: "Update the controller firmware to the same revision level as the project that is in nonvolatile memory.",
			Major:            true,
			TypeName:         "Flash Save",
		},
		43: {
			Type:             7,
			Code:             43,
			Display:          "Major Fault T07:C43 - Nonvolatile Fault: Load from nonvolatile memory failed due to bad checksum.",
			Description:      "Load from nonvolatile memory failed due to bad checksum.",
			CorrectiveAction: "Contact Rockwell Automation support.",
			Major:            true,
			TypeName:         "Flash Save",
		},
		44: {
			Type:             7,
			Code:             44,
			Display:          "Major Fault T07:C44 - Nonvolatile Fault: Failed to restore processor memory.",
			Description:      "Failed to restore controller memory.",
			CorrectiveAction: "Contact Rockwell Automation support.",
			Major:            true,
			TypeName:         "Flash Save",
		},
		49: {
			Type:             7,
			Code:             49,
			Display:          "Minor Fault T07:C49 - Nonvolatile Fault: Controller was loaded from nonvolatile memory.",
			Description:      "When the controller loads a project from nonvolatile memory, it logs this minor fault and sets the FaultLog object, MinorFaultBits attribute, bit 7.",
			CorrectiveAction: "Clear the fault.",
			Major:            false,
			TypeName:         "Flash Save",
		},
		50: {
			Type:             7,
			Code:             50,
			Display:          "Major Fault T07:C50 - Nonvolatile Fault: Security certificate invalid.",
			Description:      "The log file certificate cannot be verified. When the controller starts up, it attempts to verify the log file key/certificate combination. Depending on the verification, the controller takes one of the following actions: • If the controller verifies the existing log file certificate, the controller continues with the existing log directory. • If the existing certificate cannot be verified, the controller logs a major fault and attempts to create a certificate. • If the controller successfully creates a certificate, it creates a backup log subdirectory, moves the existing files to that directory, and continues logging and signing with the new verification key and log file certificate. •  If the controller cannot create a certificate, the controller writes log entries to the existing log directory, but does not update signature files in that directory.",
			CorrectiveAction: "Clear the fault and power cycle the controller. If the problem persists, contact Rockwell Automation support.",
			Major:            true,
			TypeName:         "Flash Save",
		},
	},
	8: {
		1: {
			Type:             8,
			Code:             1,
			Display:          "Major Fault T8:C1 - Mode Change Fault: Mode Change inhibited due to download in progress.",
			Description:      "Attempted to place controller in Run mode with keyswitch during download.",
			CorrectiveAction: "Wait for the download to complete and clear the fault.",
			Major:            true,
			TypeName:         "Mode Change",
		},
	},
	9: {
		0: {
			Type:             9,
			Code:             0,
			Display:          "Minor Fault T09:C00 - Serial Port Fault: Unknown error while servicing serial port.",
			Description:      "Unknown error while servicing the serial port.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support.",
			Major:            false,
			TypeName:         "Serial Port",
		},
		1: {
			Type:             9,
			Code:             1,
			Display:          "Minor Fault T09:C01 - Serial Port Fault: Problem with hardware control lines.",
			Description:      "The CTS line is not correct for the current configuration.",
			CorrectiveAction: "Disconnect and reconnect the serial port cable to the controller. Make sure that the cable is wired correctly.",
			Major:            false,
			TypeName:         "Serial Port",
		},
		2: {
			Type:             9,
			Code:             2,
			Display:          "Minor Fault T09:C02 - Serial Port Fault: Contents of poll list tag incorrect.",
			Description:      "Poll list error. A fault was detected with the DF1 master’s poll list, such as specifying more stations than the size of the file, specifying more than 255 stations, trying to index past the end of the list, or polling the broadcast address (STN #255).",
			CorrectiveAction: "Check for the following errors in the poll list. - Total number of stations is greater than the space in the poll list tag. - Total number of stations is greater than 255. - Current station pointer is greater than the end of the poll list tag. - A station number greater than 254 was encountered.",
			Major:            false,
			TypeName:         "Serial Port",
		},
		3: {
			Type:             9,
			Code:             3,
			Display:          "Minor Fault T09:C03 - Serial Port Fault: Master protocol missing Active Station File.",
			Description:      "The RS-232 DFI Master Active Station tag is unspecified.",
			CorrectiveAction: "Specify a tag to be used for the Active Station Tag in the System Protocol tab of the Controller Properties.",
			Major:            false,
			TypeName:         "Serial Port",
		},
		5: {
			Type:             9,
			Code:             5,
			Display:          "Minor Fault T09:C05 - Serial Port Fault: DF1 slave poll timeout.",
			Description:      "DF1 slave poll timeout. The poll watchdog has timed out for slave. The master has not polled this controller in the specified amount of time.",
			CorrectiveAction: "Determine and correct delay for polling.",
			Major:            false,
			TypeName:         "Serial Port",
		},
		9: {
			Type:             9,
			Code:             9,
			Display:          "Minor Fault T09:C09 - Serial Port Fault: Modem contact lost.",
			Description:      "Modem contact lost. DCD or DSR control lines are not being received in proper sequence or state.",
			CorrectiveAction: "Correct modem connection to the controller.",
			Major:            false,
			TypeName:         "Serial Port",
		},
		10: {
			Type:             9,
			Code:             10,
			Display:          "Minor Fault T09:C10 - Serial Port Fault: Serial Port is unable to keep up with incoming data.",
			Description:      "Data has been dropped or lost from the serial port.",
			CorrectiveAction: "Slow down the rate at which the initiator is sending data.",
			Major:            false,
			TypeName:         "Serial Port",
		},
		11: {
			Type:             9,
			Code:             11,
			Display:          "Minor Fault T09:C11 - Serial Port Fault: ACL instruction channel operand is not a valid port.",
			Description:      "A channel operand in an ACL instruction channel is not a valid port.",
			CorrectiveAction: "Correct the channel specified in the ACL instruction.",
			Major:            false,
			TypeName:         "Serial Port",
		},
	},
	10: {
		10: {
			Type:             10,
			Code:             10,
			Display:          "Minor Fault T10:C10 - Battery Fault: Battery missing or needs to be replaced.",
			Description:      "The battery is missing or must be replaced.",
			CorrectiveAction: "Install a new battery.",
			Major:            false,
			TypeName:         "Battery",
		},
		11: {
			Type:             10,
			Code:             11,
			Display:          "Minor Fault T10:C11 - Battery Fault: Safety partner battery missing or needs to be replaced.",
			Description:      "The battery for the safety partner is missing or must be replaced.",
			CorrectiveAction: "Install a new battery.",
			Major:            false,
			TypeName:         "Battery",
		},
		12: {
			Type:             10,
			Code:             12,
			Display:          "Minor Fault T10:C12 - Energy Storage Fault: Energy Storage Module not present.",
			Description:      "The energy storage module is not installed. If the controller is powered-down, the WallClockTime attribute and program are not maintained.",
			CorrectiveAction: "Install an ESM in the controller.",
			Major:            false,
			TypeName:         "Battery",
		},
		13: {
			Type:             10,
			Code:             13,
			Display:          "Minor Fault T10:C13 - Energy Storage Fault: Energy Storage Module incompatible with controller type.",
			Description:      "The installed energy storage module is not compatible with the controller.",
			CorrectiveAction: "Replace the installed ESM with one that is compatible with the controller.",
			Major:            false,
			TypeName:         "Battery",
		},
		14: {
			Type:             10,
			Code:             14,
			Display:          "Minor Fault T10:C14 - Energy Storage Fault: Energy Storage Module hardware failure.",
			Description:      "The energy storage module must be replaced due to a hardware fault. It is not capable of maintaining the WallClockTime attribute or controller program at power down.",
			CorrectiveAction: "Replace the ESM.",
			Major:            false,
			TypeName:         "Battery",
		},
		15: {
			Type:             10,
			Code:             15,
			Display:          "Minor Fault T10:C15 - Energy Storage Fault: Energy Storage Module energy low.",
			Description:      "The energy storage module cannot store enough energy to maintain the WallClockTime attribute or the controller program at power-down.",
			CorrectiveAction: "Replace the ESM.",
			Major:            false,
			TypeName:         "Battery",
		},
		16: {
			Type:             10,
			Code:             16,
			Display:          "Minor Fault T10:C16 - UPS Fault: UPS missing or not ready.",
			Description:      "The uninterruptible power supply is missing or not ready.",
			CorrectiveAction: "Either: • Install the UPS. • Check the UPS to make sure it is adequately charged to provide backup power if there is a power loss.",
			Major:            false,
			TypeName:         "Battery",
		},
		17: {
			Type:             10,
			Code:             17,
			Display:          "Minor Fault T10:C17 - UPS Fault: UPS battery failure.",
			Description:      "The uninterruptible power supply battery has failed and must be replaced.",
			CorrectiveAction: "Replace the battery in the UPS.",
			Major:            false,
			TypeName:         "Battery",
		},
	},
	11: {
		1: {
			Type:             11,
			Code:             1,
			Display:          "Major Fault T11:C01 - Motion Fault: Actual position of axis exceeded positive overtravel limit.",
			Description:      "The actual position of the axis has exceeded the positive overtravel limit.",
			CorrectiveAction: "Move axis in negative direction until the position is within the overtravel limit and then execute Motion Axis Fault Reset.",
			Major:            true,
			TypeName:         "Motion",
		},
		2: {
			Type:             11,
			Code:             2,
			Display:          "Major Fault T11:C02 - Motion Fault: Actual position of axis exceeded negative overtravel limit.",
			Description:      "The actual position of the axis has exceeded the negative overtravel limit.",
			CorrectiveAction: "Move axis in positive direction until position is within the overtravel limit and then run Motion Axis Fault Reset.",
			Major:            true,
			TypeName:         "Motion",
		},
		3: {
			Type:             11,
			Code:             3,
			Display:          "Major Fault T11:C03 - Motion Fault: Actual position exceeded position error tolerance.",
			Description:      "The actual position the axis has exceeded the position error tolerance.",
			CorrectiveAction: "Move the position within tolerance, then run Motion Axis Fault Reset.",
			Major:            true,
			TypeName:         "Motion",
		},
		4: {
			Type:             11,
			Code:             4,
			Display:          "Major Fault T11:C04 - Motion Fault: Encode channel A, B, or Z connection failed.",
			Description:      "Encoder channel A, B, or Z connection is broken.",
			CorrectiveAction: "Reconnect the encoder channel, then run Motion Axis Fault Reset.",
			Major:            true,
			TypeName:         "Motion",
		},
		5: {
			Type:             11,
			Code:             5,
			Display:          "Major Fault T11:C05 - Motion Fault: Encoder noise event detected, or encoder signals not in quadrature.",
			Description:      "Encoder noise event detected or the encoder signals are not in the quadrature.",
			CorrectiveAction: "Fix encoder cabling, then run Motion Axis Fault Reset.",
			Major:            true,
			TypeName:         "Motion",
		},
		6: {
			Type:             11,
			Code:             6,
			Display:          "Major Fault T11:C06 - Motion Fault: Drive fault.",
			Description:      "Drive fault detected.",
			CorrectiveAction: "Clear Drive Fault then run Motion Axis Fault Reset.",
			Major:            true,
			TypeName:         "Motion",
		},
		7: {
			Type:             11,
			Code:             7,
			Display:          "Major Fault T11:C07 - Motion Fault: Synchronous connection to servo module failed.",
			Description:      "Synchronous connection to the servo module failed.",
			CorrectiveAction: "Try these steps: 1. First, run Motion Axis Fault Reset. 2. If that does not work, pull out the servo module and plug it back in. 3. If this does not work, replace the servo module.",
			Major:            true,
			TypeName:         "Motion",
		},
		8: {
			Type:             11,
			Code:             8,
			Display:          "Major Fault T11:C08 - Motion Fault: Hardware failure in servo module.",
			Description:      "Hardware failure detected in the servo module.",
			CorrectiveAction: "Replace the module.",
			Major:            true,
			TypeName:         "Motion",
		},
		9: {
			Type:             11,
			Code:             9,
			Display:          "Major Fault T11:C09 - Motion Fault: Asynchronous connection to servo module failed.",
			Description:      "Asynchronous connection to the servo module failed.",
			CorrectiveAction: "Try these steps: 1. First, run Motion Axis Fault Reset. 2. If that does not work, pull out the servo module and plug it back in. 3. If this does not work, replace the servo module.",
			Major:            true,
			TypeName:         "Motion",
		},
		10: {
			Type:             11,
			Code:             10,
			Display:          "Major Fault T11:C10 - Motion Fault: Motor fault detected.",
			Description:      "Motor fault detected.",
			CorrectiveAction: "See the DriveFaults axis tag for more information.",
			Major:            true,
			TypeName:         "Motion",
		},
		11: {
			Type:             11,
			Code:             11,
			Display:          "Major Fault T11:C11 - Motion Fault: Motor thermal fault detected.",
			Description:      "Motor thermal fault detected.",
			CorrectiveAction: "See the DriveFaults axis tag for more information.",
			Major:            true,
			TypeName:         "Motion",
		},
		12: {
			Type:             11,
			Code:             12,
			Display:          "Major Fault T11:C12 - Motion Fault: Drive thermal fault detected.",
			Description:      "Drive thermal fault detected.",
			CorrectiveAction: "See the DriveFaults axis tag for more information.",
			Major:            true,
			TypeName:         "Motion",
		},
		13: {
			Type:             11,
			Code:             13,
			Display:          "Major Fault T11:C13 - Motion Fault: SERCOS comm fault detected.",
			Description:      "SERCOS communication fault detected.",
			CorrectiveAction: "Verify the integrity of the SERCOS fiber-optic ring network and the devices on it.",
			Major:            true,
			TypeName:         "Motion",
		},
		14: {
			Type:             11,
			Code:             14,
			Display:          "Major Fault T11:C14 - Motion Fault: Drive Enable Input 1) was inactive prior during an attempt to enable the drive, or 2) transitioned to inactive while the drive was enabled.",
			Description:      "Drive enable input was inactive during an attempt to enable the drive or transitioned to inactive while the drive was enabled.",
			CorrectiveAction: "Re-enable the drive enable input and clear the fault.",
			Major:            true,
			TypeName:         "Motion",
		},
		15: {
			Type:             11,
			Code:             15,
			Display:          "Major Fault T11:C15 - Motion Fault: Drive Phase Loss fault detected.",
			Description:      "Drive phase loss fault detected.",
			CorrectiveAction: "Restore full power connection to the drive and clear the fault.",
			Major:            true,
			TypeName:         "Motion",
		},
		16: {
			Type:             11,
			Code:             16,
			Display:          "Major Fault T11:C16 - Motion Fault: A Guard Fault has been detected by the drive.",
			Description:      "DriveGuard® fault detected.",
			CorrectiveAction: "See the GuardFaults axis tag for more information.",
			Major:            true,
			TypeName:         "Motion",
		},
		32: {
			Type:             11,
			Code:             32,
			Display:          "Major Fault T11:C32 - Motion Fault: Motion Task overlap.  Coarse update rate too high.",
			Description:      "The motion task experienced an overlap. The coarse update rate is too high.",
			CorrectiveAction: "The group’s course update rate is too high to maintain correct operation. Clear the group fault tag, raise the group’s update rate, and then clear the major fault.",
			Major:            true,
			TypeName:         "Motion",
		},
		33: {
			Type:             11,
			Code:             33,
			Display:          "Major Fault T11:C33 - Motion Fault: Coordinated System Time reference has been lost.",
			Description:      "Coordinated System Time reference has been lost.",
			CorrectiveAction: "Check the condition of the CST master in the backplane. ",
			Major:            true,
			TypeName:         "Motion",
		},
	},
	12: {
		32: {
			Type:             12,
			Code:             32,
			Display:          "Major Fault T12:C32 - Safety Fault: Disqualified secondary became primary.",
			Description:      "A disqualified secondary controller cycled power and no partner chassis or controller was found upon power-up.",
			CorrectiveAction: "Verify the following: •  A partner chassis is connected. • Power is applied to both redundant chassis. • Partner controllers have the same catalog number, slot number, and firmware revision.",
			Major:            true,
			TypeName:         "Redundancy",
		},
		33: {
			Type:             12,
			Code:             33,
			Display:          "Major Fault T12:C33 - Safety Fault: No partner found after switchover.",
			Description:      "An unpartnered controller has been identified in the new primary chassis after a switchover.",
			CorrectiveAction: "Use these methods: • Remove the unpartnered controller and troubleshoot the cause of the switchover. • Add a partner controller to the secondary chassis, troubleshoot the cause of the switchover, and synchronize the system.",
			Major:            true,
			TypeName:         "Redundancy",
		},
		34: {
			Type:             12,
			Code:             34,
			Display:          "Major Fault T12:C34 - Safety Fault: Keyswitch Positions of Primary and Secondary Controllers Mismatched",
			Description:      "Before switchover, a keyswitch mismatch was present. The old primary controller was in Program mode and the keyswitch of the secondary partner was in the Run position.  Instead of the switchover transitioning the new primary controller to go to Run mode, the new primary controller transitions to a faulted state after the switchover.",
			CorrectiveAction: "Use these methods: • Change the keyswitches from Run mode to Program mode and back to Run mode twice to clear the fault. Make sure that the keyswitch positions for both controllers in a partnered set match. • Use the programming software to go online with the controllers. Then, clear the faults and change the keyswitch positions for both the controllers in the partnered set to Run.",
			Major:            true,
			TypeName:         "Redundancy",
		},
	},
	13: {
		21: {
			Type:             13,
			Code:             21,
			Display:          "Minor Fault T13:C21 - Real Time Clock Fault: Wall Clock Time out of range.",
			Description:      "The WallClockTime is out of range.",
			CorrectiveAction: "Verify the WallClockTime is set to the correct date/time.",
			Major:            false,
			TypeName:         "Real Time Clock",
		},
	},
	14: {
		1: {
			Type:             14,
			Code:             1,
			Display:          "Task Watchdog Expired",
			Description:      "The task watchdog expired because of these reasons: • The user task did not complete in a specified period of time. • A program error caused an infinite loop. • The program is too complex to execute as quickly as specified. • A higher priority task is keeping this task from finishing. • The safety partner has been removed.",
			CorrectiveAction: "(GuardLogix® 5580 and Compact GuardLogix® 5380 only). Clear the fault. Safety memory is reinitialized and the safety task begins executing. Reinsert the safety partner if it was removed.  (GuardLogix® 5570 and Compact GuardLogix® 5370 only). Clear the fault. If a safety task signature exists, safety memory is reinitialized and the safety task begins executing. If a safety task signature does not exist, you must redownload the program to allow the safety task to run. Reinsert the safety partner if it was removed.",
			Major:            true,
			TypeName:         "Nonrecoverable",
		},
		2: {
			Type:             14,
			Code:             2,
			Display:          "Major Fault T14:C02 - Safety Task Fault: An error exists in a routine of the Safety task.",
			Description:      "An error exists in a routine of the safety task.",
			CorrectiveAction: "Correct the error in the user-program logic.",
			Major:            true,
			TypeName:         "Recoverable",
		},
		3: {
			Type:             14,
			Code:             3,
			Display:          "Major Fault T14:C03 - Safety Task Fault: Safety partner is missing.",
			Description:      "The safety partner is missing.",
			CorrectiveAction: "Install a compatible safety partner and clear the fault. A download may be required. ",
			Major:            true,
			TypeName:         "Nonrecoverable",
		},
		4: {
			Type:             14,
			Code:             4,
			Display:          "Major Fault T14:C04 - Safety Task Fault: Safety partner is unavailable.",
			Description:      "The safety partner is unavailable.",
			CorrectiveAction: "Install a compatible safety partner and clear the fault. A download may be required. ",
			Major:            true,
			TypeName:         "Nonrecoverable",
		},
		5: {
			Type:             14,
			Code:             5,
			Display:          "Major Fault T14:C05 - Safety Task Fault: Safety partner hardware is incompatible.",
			Description:      "The safety partner hardware is incompatible.",
			CorrectiveAction: "Install a compatible safety partner and clear the fault. A download may be required. ",
			Major:            true,
			TypeName:         "Nonrecoverable",
		},
		6: {
			Type:             14,
			Code:             6,
			Display:          "Major Fault T14:C06 - Safety Task Fault: Safety partner firmware is incompatible.",
			Description:      "The safety partner firmware is incompatible.",
			CorrectiveAction: "Update the safety partner so that the firmware major and minor revisions match the primary controller. A download may be required. ",
			Major:            true,
			TypeName:         "Nonrecoverable",
		},
		7: {
			Type:             14,
			Code:             7,
			Display:          "Major Fault T14:C07 - Safety Task Fault: Safety task is inoperable.",
			Description:      "The safety task is inoperable. This fault occurs when the safety logic is invalid, such as for these reasons: • A mismatch in logic exists between the primary controller and safety partners. • A watchdog timeout occurs. • Memory is corrupt.",
			CorrectiveAction: "(GuardLogix® 5580 only). Clear the fault and download the application.  (GuardLogix® 5570 only). Clear the fault. If a safety task signature exists, safety memory is reinitialized via the safety task signature and the safety task begins executing. If a safety task signature does not exist, you must download the program again to allow the safety task to run.",
			Major:            true,
			TypeName:         "Nonrecoverable",
		},
		8: {
			Type:             14,
			Code:             8,
			Display:          "Major Fault T14:C08 - Safety Task Fault: Safety partner's time is not synchronized with primary.",
			Description:      "Coordinated system time (CST) not found. The safety partner's time is not synchronized with the primary.",
			CorrectiveAction: "Clear the fault. Configure a device to be the CST master.",
			Major:            true,
			TypeName:         "Nonrecoverable",
		},
		9: {
			Type:             14,
			Code:             9,
			Display:          "Major Fault T14:C09 - Safety Task Fault: A non-recoverable fault has occurred in safety partner.",
			Description:      "The safety partner detected a nonrecoverable major fault. Diagnostic information can be recovered.",
			CorrectiveAction: "Insert a memory card in the safety partner and restart the safety partner to write diagnostic information to the memory card. Then clear the fault and download the application. Contact Rockwell Automation support.",
			Major:            true,
			TypeName:         "Nonrecoverable",
		},
		10: {
			Type:             14,
			Code:             10,
			Display:          "Safety Fault",
			Description:      "A cross-compare fault was detected between the two controllers.",
			CorrectiveAction: "Clear the fault and download the application. If the problem persists, replace the controller.",
			Major:            true,
			TypeName:         "Nonrecoverable",
		},
		11: {
			Type:             14,
			Code:             11,
			Display:          "Safety Task Fault",
			Description:      "The safety task failed to recover during a loss of redundancy. The maximum safety mute time was exceeded.",
			CorrectiveAction: "Clear the fault and download the application. If the problem persists, replace the controller.",
			Major:            true,
			TypeName:         "Nonrecoverable",
		},
		12: {
			Type:             14,
			Code:             12,
			Display:          "Minor Fault T14:C12 - Safety Fault: Safety partner detected when the project safety level is SIL2/PLd.",
			Description:      "The safety partner was detected when the project safety level is SIL2/PLd.",
			CorrectiveAction: "If your desired safety level is SIL2/PLd, remove the safety partner (since it does not participate in a SIL2/PLd configuration). If your desired safety level is SIL3/PLe, change the project safety level to SIL3/PLe.",
			Major:            false,
			TypeName:         "Safety",
		},
		13: {
			Type:             14,
			Code:             13,
			Display:          "Safety Fault",
			Description:      "A data integrity error occurred between the primary and secondary chassis.",
			CorrectiveAction: "Clear the fault and download the application. If the problem persists, replace the controller.",
			Major:            true,
			TypeName:         "Nonrecoverable",
		},
	},
	16: {
		1: {
			Type:             16,
			Code:             1,
			Display:          "Communication Configuration Fault",
			Description:      "The controller log is full and data is being overwritten.",
			CorrectiveAction: "Configure the controller to write buffered entries to the memory card when its internal buffer is 80% full. or Command the controller to write buffered entries to removable media with an MSG instruction.",
			Major:            false,
			TypeName:         "Communication",
		},
	},
	17: {
		0: {
			Type:             17,
			Code:             0,
			Display:          "Minor Fault T17:C00 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		1: {
			Type:             17,
			Code:             1,
			Display:          "Minor Fault T17:C01 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		2: {
			Type:             17,
			Code:             2,
			Display:          "Minor Fault T17:C02 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		3: {
			Type:             17,
			Code:             3,
			Display:          "Minor Fault T17:C03 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		4: {
			Type:             17,
			Code:             4,
			Display:          "Minor Fault T17:C04 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		5: {
			Type:             17,
			Code:             5,
			Display:          "Minor Fault T17:C05 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		6: {
			Type:             17,
			Code:             6,
			Display:          "Minor Fault T17:C06 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		7: {
			Type:             17,
			Code:             7,
			Display:          "Minor Fault T17:C07 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		8: {
			Type:             17,
			Code:             8,
			Display:          "Minor Fault T17:C08 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		9: {
			Type:             17,
			Code:             9,
			Display:          "Minor Fault T17:C09 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		10: {
			Type:             17,
			Code:             10,
			Display:          "Minor Fault T17:C10 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		11: {
			Type:             17,
			Code:             11,
			Display:          "Minor Fault T17:C11 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		12: {
			Type:             17,
			Code:             12,
			Display:          "Minor Fault T17:C12 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		13: {
			Type:             17,
			Code:             13,
			Display:          "Minor Fault T17:C13 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		14: {
			Type:             17,
			Code:             14,
			Display:          "Minor Fault T17:C14 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		15: {
			Type:             17,
			Code:             15,
			Display:          "Minor Fault T17:C15 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		16: {
			Type:             17,
			Code:             16,
			Display:          "Minor Fault T17:C16 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		17: {
			Type:             17,
			Code:             17,
			Display:          "Minor Fault T17:C17 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		18: {
			Type:             17,
			Code:             18,
			Display:          "Minor Fault T17:C18 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		19: {
			Type:             17,
			Code:             19,
			Display:          "Minor Fault T17:C19 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed. Upload and save the program before the controller is powered down. ",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		20: {
			Type:             17,
			Code:             20,
			Display:          "Minor Fault T17:C20 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		21: {
			Type:             17,
			Code:             21,
			Display:          "Minor Fault T17:C21 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed. Upload and save program before the controller is powered down. ",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		22: {
			Type:             17,
			Code:             22,
			Display:          "Minor Fault T17:C22 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		23: {
			Type:             17,
			Code:             23,
			Display:          "Minor Fault T17:C23 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		24: {
			Type:             17,
			Code:             24,
			Display:          "Minor Fault T17:C24 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		25: {
			Type:             17,
			Code:             25,
			Display:          "Minor Fault T17:C25 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed.",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		26: {
			Type:             17,
			Code:             26,
			Display:          "Minor Fault T17:C26 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed. Upload and save the program before the controller is powered down. ",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		27: {
			Type:             17,
			Code:             27,
			Display:          "Minor Fault T17:C27 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed. Upload and save the program before the controller is powered down. ",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		28: {
			Type:             17,
			Code:             28,
			Display:          "Minor Fault T17:C28 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed. Upload and save the program before the controller is powered down. ",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		29: {
			Type:             17,
			Code:             29,
			Display:          "Minor Fault T17:C29 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed. Upload and save the program before the controller is powered down. ",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		30: {
			Type:             17,
			Code:             30,
			Display:          "Minor Fault T17:C30 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed. Upload and save the program before the controller is powered down. ",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		31: {
			Type:             17,
			Code:             31,
			Display:          "Minor Fault T17:C31 - Diagnostic Fault: A runtime diagnostic failed to complete, please contact technical support with the fault type and fault code.",
			Description:      "An internal controller diagnostic failed. Upload and save the program before the controller is powered down. ",
			CorrectiveAction: "Contact Rockwell Automation Technical Support with the fault type and fault code logged.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		32: {
			Type:             17,
			Code:             31,
			Display:          "Major Fault T17:C34 - Diagnostic Fault: Controller internal temperature has exceeded operating limit.",
			Description:      "Controller internal temperature has exceeded the operating limit.",
			CorrectiveAction: "Take measures to reduce the ambient temperature of the module. Follow the recommended limits for the ambient (inlet) temperature and apply the required clearance around the chassis.",
			Major:            true,
			TypeName:         "Diagnostic",
		},
		35: {
			Type:             17,
			Code:             35,
			Display:          "Minor Fault T17:C35 - Diagnostic Fault: Controller internal temperature is approaching operating limit.",
			Description:      "Controller internal temperature is approaching the operating limit.",
			CorrectiveAction: "Take measures to reduce the ambient temperature of the module. Follow the recommended limits for the ambient (inlet) temperature and apply the required clearance around the chassis.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		36: {
			Type:             17,
			Code:             36,
			Display:          "Minor Fault T17:C36 - Diagnostic Fault: A fan has been removed, or is not maintaining desired speed.",
			Description:      "A fan has been removed, or is not maintaining the desired speed.",
			CorrectiveAction: "Check the device fans for connection or maintenance issues.",
			Major:            false,
			TypeName:         "Diagnostic",
		},
		37: {
			Type:             17,
			Code:             37,
			Display:          "Major Fault T17:C37 - Diagnostic Fault: Controller has recovered from an internal temperature fault.",
			Description:      "The controller has recovered from an internal temperature fault.",
			CorrectiveAction: "Generated when the controller recovers from automatic shutdown. Shutdown occurs when the module temperature exceeds the temperature threshold of the preservation fault. When the temperature decreases to a suitable level, this re-enables the controller voltages and generates the Type 17, Code 37 fault.",
			Major:            true,
			TypeName:         "Runtime Diagnostic",
		},
	},
	18: {
		1: {
			Type:             18,
			Code:             1,
			Display:          "Major Fault T18:C01 - CIP Motion Fault: A standard Initialization Fault has been detected by the drive.",
			Description:      "The drive did not initialize correctly.",
			CorrectiveAction: "To determine corrective action, see the Initialization Fault attributes. The corresponding bit indicates the cause of the fault. 1: Boot Block Checksum Fault 2: Main Block Checksum Fault 3: Nonvolatile Memory Checksum Fault",
			Major:            true,
			TypeName:         "Integrated motion on the EtherNet/IP™ network",
		},
		2: {
			Type:             18,
			Code:             2,
			Display:          "Major Fault T18:C02 - CIP Motion Fault: A manufacturer specific Initialization Fault has been detected by the drive.",
			Description:      "The drive did not initialized correctly. This fault indicates a manufacturer-specific initialization fault.",
			CorrectiveAction: "To determine corrective action, see the Initialization Fault Mfg attributes. The corresponding bit indicates the cause of the fault. 1: Feedback Data Corruption 2: Feedback Data Range 3: Feedback Communication Startup 4: Feedback Absolute Overspeed 5: Feedback Absolute Power Off Travel 6: Feedback Absolute Startup Speed 7: Commutation Offset Uninitialized 12: Invalid FPGA Image 14: Invalid Safety Firmware 15: Power Board 16: Illegal Option Card 17: Option Storage Checksum 19: Module Voltage Mismatch 20: Unknown Module 21: Factory Configuration Error 22: Illegal Address 23: Series Mismatch 24: Open Slot",
			Major:            true,
			TypeName:         "CIP Motion",
		},
		3: {
			Type:             18,
			Code:             3,
			Display:          "Major Fault T18:C03 - CIP Motion Fault: A standard Axis Fault has been detected by the drive.",
			Description:      "There is a fault on the physical axis.",
			CorrectiveAction: "To determine corrective action, see the Axis Fault attributes. The corresponding bit indicates the cause of the fault.",
			Major:            true,
			TypeName:         "CIP Motion",
		},
		4: {
			Type:             18,
			Code:             4,
			Display:          "Major Fault T18:C04 - CIP Motion Fault: A manufacturer specific Axis Fault has been detected by the drive.",
			Description:      "There is a fault on the physical axis. This fault indicates a manufacturer-specific axis fault",
			CorrectiveAction: "To determine corrective action, see the Axis Fault Mfg attributes. The corresponding bit indicates the cause of the fault.",
			Major:            true,
			TypeName:         "CIP Motion",
		},
		5: {
			Type:             18,
			Code:             5,
			Display:          "Major Fault T18:C05 - CIP Motion Fault: A Motion Fault has been detected by the drive.",
			Description:      "A motion fault detected.",
			CorrectiveAction: "To determine corrective action, see the Motion Fault attribute and Motion Fault bits for details about the fault that occurred.",
			Major:            true,
			TypeName:         "CIP Motion",
		},
		6: {
			Type:             18,
			Code:             6,
			Display:          "Major Fault T18:C06 - CIP Motion Fault: A Module Fault has been detected by the drive.",
			Description:      "A motion drive fault detected. Usually the fault affects all axes that are associated with the module and all associated axes are shut down.",
			CorrectiveAction: "Reconfigure the faulted motion module to correct the fault.",
			Major:            true,
			TypeName:         "CIP Motion",
		},
		7: {
			Type:             18,
			Code:             7,
			Display:          "Major Fault T18:C07 - CIP Motion Fault: Group Fault",
			Description:      "A motion group fault detected. Usually the fault affects all axes that are associated with a motion group.",
			CorrectiveAction: "Reconfigure the entire motion subsystem to correct the fault. See the Group Fault attribute if details about the fault are needed.",
			Major:            true,
			TypeName:         "CIP Motion",
		},
		8: {
			Type:             18,
			Code:             8,
			Display:          "Major Fault T18:C08 - CIP Motion Fault: A Configuration Fault has been detected by the drive.",
			Description:      "A fault occurred during the configuration of a motion drive. Typically, this fault occurs when an attempt to update an axis configuration attribute of a drive was unsuccessful.",
			CorrectiveAction: "To determine the corrective action, see the Configuration Fault in the Attribute Error Code and Attribute Error ID attributes associated with the motion or 1756-ENxT module.",
			Major:            true,
			TypeName:         "CIP Motion",
		},
		9: {
			Type:             18,
			Code:             9,
			Display:          "Major Fault T18:C09 - CIP Motion Fault: A standard APR Fault has been detected by the drive.",
			Description:      "An Absolute Position Recovery (APR) fault occurred and the absolute position of the axis cannot be recovered.",
			CorrectiveAction: "To determine the corrective action, see the APR Fault attributes. The corresponding bit indicates the cause of the fault. 1: Memory Write Error 2: Memory Read Error 3: Feedback Serial Number Mismatch 4: Buffer Allocation Fault 5: Scaling Configuration Changed 6: Feedback Mode Changed 7: Feedback Integrity Loss",
			Major:            true,
			TypeName:         "CIP Motion",
		},
		10: {
			Type:             18,
			Code:             10,
			Display:          "Major Fault T18:C10 - CIP Motion Fault: A manufacturer specific APR Fault has been detected by the drive.",
			Description:      "An Absolute Position Recovery (APR) Fault occurred and the absolute position of the axis cannot be recovered. This fault indicates a manufacturer-specific APR fault.",
			CorrectiveAction: "To determine the corrective action, see the APR Fault Mfg attributes.  The corresponding bit indicates the cause of the fault.",
			Major:            true,
			TypeName:         "CIP Motion",
		},
	},
	19: {
		1: {
			Type:             19,
			Code:             1,
			Display:          "Minor Fault T19:C01 - Ethernet Port Fault",
			Description:      "The controller detected that another device on the network already has the IP address of the controller. ",
			CorrectiveAction: "Do one of the following: • Identify the device with the same IP address as the controller and change its IP address. • Change the IP address of the controller, so that it does not conflict with any other device.",
			Major:            false,
			TypeName:         "Ethernet Port",
		},
		2: {
			Type:             19,
			Code:             2,
			Display:          "Minor Fault T19:C02 - Ethernet Port Fault",
			Description:      "The DHCP server replied with an invalid IP address.",
			CorrectiveAction: "Check the DHCP server configuration.",
			Major:            false,
			TypeName:         "Ethernet Port",
		},
		3: {
			Type:             19,
			Code:             3,
			Display:          "Minor Fault T19:C03 - Ethernet Port Fault",
			Description:      "The DHCP lease was lost or its renewal failed.",
			CorrectiveAction: "Check the DHCP server availability and configuration.",
			Major:            false,
			TypeName:         "Ethernet Port",
		},
		4: {
			Type:             19,
			Code:             4,
			Display:          "Minor Fault T19:C04 - Ethernet Port Fault",
			Description:      "0x00000000",
			CorrectiveAction: "Investigate network traffic on the Ethernet port and clear the fault. If problems persist, contact Rockwell Automation Technical Support for further assistance.",
			Major:            false,
			TypeName:         "Ethernet Port",
		},
	},
	20: {
		1: {
			Type:             20,
			Code:             1,
			Display:          "Major Fault T20:C01 - License Fault: License is missing or invalid.",
			Description:      "A required license is missing or expired during the transition to Run or Test mode.",
			CorrectiveAction: "Insert a CmCard which contains all licenses that are required by the project in the controller.",
			Major:            true,
			TypeName:         "License Protection",
		},
		2: {
			Type:             20,
			Code:             2,
			Display:          "Minor Fault T20:C02 - License Fault: License has expired.",
			Description:      "The License Based Execution Protection license that is stored on the CmCard has the correct license, but it has expired.",
			CorrectiveAction: "Obtain a CmCard with the correct unexpired license and insert it into the controller.",
			Major:            false,
			TypeName:         "License Protection",
		},
	},
	21: {
		1: {
			Type:             21,
			Code:             1,
			Display:          "Minor Fault T21:C01 - Alarm Fault: Evaluating alarms exceeded the evaluation period.",
			Description:      "Evaluating alarms exceeded the evaluation period.",
			CorrectiveAction: "If the fault occurs for a controller that experiences a regular active alarm rate (not alarm burst) for tag-based alarms during system commissioning, then reduce the number of the alarms in the project. Otherwise, the fault is an indicator for the operator that tag-based alarm state information can be older than the evaluation period (only 500 ms evaluation period). ",
			Major:            false,
			TypeName:         "Alarm",
		},
		2: {
			Type:             21,
			Code:             2,
			Display:          "Minor Fault T21:C02 - Alarm Fault: Alarm set highest severity alarm data may be inaccurate.",
			Description:      "Alarm set highest severity alarm data may be inaccurate.",
			CorrectiveAction: "If the fault occurs for a controller that experiences a regular active alarm rate (not alarm burst) for tag-based alarms during the system commissioning, then reduce the number of the alarms in the project. Otherwise, the fault is an indicator for the operator that information about the Alarm Set highest severity can be older than 2 seconds.",
			Major:            false,
			TypeName:         "Alarm",
		},
	},
}
